name: "Test Dispatch event"
on:
  repository_dispatch:
    types: ["category-tag-created"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORDPRESS_API_URL: https://wp.thestackjournal.com/graphql
      FROM_EMAIL: thestackjournal@gmail.com
      TO_EMAIL: thestackjournal@gmail.com
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DOCUWOMEN_PAT }}

      - name: setup node
        uses: actions/setup-node@v2

      - name: install deps
        run: |
          npm install

      - name: run build
        run: npm run build

      - name: Push empty commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit --allow-empty -m "Empty commit to trigger deploy"
          git push

      # - name: Push with AD-M
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
