name: "Test Dispatch event"
on:
  repository_dispatch:
    types: ["category-tag-created"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Push empty commit
        run: |
          git commit --allow-empty -am "Empty commit to trigger deploy" && git push origin main
